#!/bin/bash -xe

# pull in magento repo
git clone https://github.com/magento/magento2 --depth=1

# generate a base workspace.json to work from
npm run generate-workspace

# generate and display graph
npx nx dep-graph
npx nx dep-graph --verbose --skip-nx-cache


export NX_VERBOSE_LOGGING=true
export NX_CACHE_PROJECT_GRAPH=false
export NX_DAEMON=false


php8.0 ./php-classes.phar magento2/app/code/Magento/AdminNotification/Observer/PredispatchAdminActionControllerObserver.php
